//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.Book {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblISBN;
		protected global::System.Web.UI.WebControls.TextBox txtbookTitle;
		protected global::System.Web.UI.WebControls.TextBox txtauthor;
		protected global::System.Web.UI.WebControls.TextBox txtpublishDate;
		protected global::System.Web.UI.WebControls.TextBox txtversion;
		protected global::System.Web.UI.WebControls.TextBox txtstockNumber;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtsalePrice;
		protected global::System.Web.UI.WebControls.TextBox txtintroduction;
		protected global::System.Web.UI.WebControls.TextBox txtcatalog;
		protected global::System.Web.UI.WebControls.TextBox txtcategoryId;
		protected global::System.Web.UI.WebControls.TextBox txtpressNo;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
