//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.OrderSheet {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtorderNo;
		protected global::System.Web.UI.WebControls.TextBox txtmemberNo;
		protected global::System.Web.UI.WebControls.TextBox txtemployeeNo;
		protected global::System.Web.UI.WebControls.TextBox txtorderDate;
		protected global::System.Web.UI.WebControls.TextBox txtorderMoney;
		protected global::System.Web.UI.WebControls.TextBox txtpayWay;
		protected global::System.Web.UI.WebControls.TextBox txtpayFlag;
		protected global::System.Web.UI.WebControls.TextBox txtorderState;
		protected global::System.Web.UI.WebControls.TextBox txtinvoiceUnit;
		protected global::System.Web.UI.WebControls.TextBox txtreceiver;
		protected global::System.Web.UI.WebControls.TextBox txtzipCode;
		protected global::System.Web.UI.WebControls.TextBox txtshipAddress;
		protected global::System.Web.UI.WebControls.TextBox txtshipTel;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
