//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.OrderSheet {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblorderNo;
	protected global::System.Web.UI.WebControls.Label lblmemberNo;
	protected global::System.Web.UI.WebControls.Label lblemployeeNo;
	protected global::System.Web.UI.WebControls.Label lblorderDate;
	protected global::System.Web.UI.WebControls.Label lblorderMoney;
	protected global::System.Web.UI.WebControls.Label lblpayWay;
	protected global::System.Web.UI.WebControls.Label lblpayFlag;
	protected global::System.Web.UI.WebControls.Label lblorderState;
	protected global::System.Web.UI.WebControls.Label lblinvoiceUnit;
	protected global::System.Web.UI.WebControls.Label lblreceiver;
	protected global::System.Web.UI.WebControls.Label lblzipCode;
	protected global::System.Web.UI.WebControls.Label lblshipAddress;
	protected global::System.Web.UI.WebControls.Label lblshipTel;


       
    }
}
