//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.Employee {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblemployeeNo;
		protected global::System.Web.UI.WebControls.TextBox txtempPassword;
		protected global::System.Web.UI.WebControls.TextBox txtempName;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtbirthday;
		protected global::System.Web.UI.WebControls.TextBox txtdepartment;
		protected global::System.Web.UI.WebControls.TextBox txttitle;
		protected global::System.Web.UI.WebControls.TextBox txtsalary;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txttelephone;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
