//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.Company {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcompantNo;
		protected global::System.Web.UI.WebControls.TextBox txtcompanyName;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txtzipCode;
		protected global::System.Web.UI.WebControls.TextBox txtcontactPerson;
		protected global::System.Web.UI.WebControls.TextBox txttelephone;
		protected global::System.Web.UI.WebControls.TextBox txtfax;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
